name: verify

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 21, 22, 23 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with JDK ${{ matrix.java-version }}
        run: ./gradlew build